#!/usr/bin/python
# Author:			Billy O Sullivan
# Script name:			quick_templates.py
# Purpose: 			This script copies the text of certain 
#				textfiles to the clipboard when a button is pressed
# Created: 			09 September 2017
# Last Edited by & date:	Billy O Sullivan - 09 September 2017


from Tkinter import *
import pyperclip

def temp(opt):
	if opt == 1:
		doc = open('doc1.txt', 'r').read()
		pyperclip.copy(doc)
	elif opt == 2:
		doc = open('doc2.txt', 'r').read()
		pyperclip.copy(doc)
	elif opt == 3:
		doc = open('doc3.txt', 'r').read()
		pyperclip.copy(doc)
	elif opt == 4:
		doc = open('doc4.txt', 'r').read()
		pyperclip.copy(doc)
	elif opt == 5:
		doc = open('doc5.txt', 'r').read()
		pyperclip.copy(doc)


app = Tk()
app.title("quick_template.py")
button1 = Button(app, text="template 1", bg='green', command=lambda: temp(1))
button1.grid(row=0,column=1, columnspan=1)
button2 = Button(app, text="template 2", bg='green', command=lambda: temp(2))
button2.grid(row=0,column=2, sticky=N, columnspan=1)
button3 = Button(app, text="template 3", bg='green', command=lambda: temp(3))
button3.grid(row=0,column=3, sticky=N, columnspan=1)
button4 = Button(app, text="template 4", bg='green', command=lambda: temp(4))
button4.grid(row=0,column=4, sticky=N, columnspan=1)
button5 = Button(app, text="template 5", bg='green', command=lambda: temp(5))
button5.grid(row=0,column=5, sticky=N, columnspan=1)
mainloop()	
